name: Metrics

on:
  schedule: [{cron: "0 * * * *"}] # Atualiza a cada hora
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: seu-usuario # Substitua pelo seu nome de usuário do GitHub
          template: classic
          base: header, activity, community, repositories, metadata
